<?php

/**
 * @file
 * This the main module file.
 */

function references_menu() {
  $items = array();
  // This redirect callback is used when adding and editing content in
  // the overlay. When content is created or edited, we are directed here,
  // so we can act properly on entities.
  $items['references-dialog/redirect/%/%'] = array(
    'page callback' => 'references_dialog_redirect_page',
    'page arguments' => array(2,3),
    'access callback' => 'references_dialog_redirect_access',
    'access arguments' => array(2,3),
  );
  return $items;
}

/**
 * Implements hook_field_widget_info().
 */
function references_dialog_field_widget_info() {
  return array(
    'references_dialog_dialog' => array(
      'label'       => t('Autocomplete text field with dialog'),
      'description' => t('Display the list of referenceable nodes as a textfield with autocomplete behaviour.'),
      'field types' => array('node_reference', 'user_reference'),
      'settings'    => array(
        'autocomplete_match' => 'contains',
        'size' => 60,
        'autocomplete_path' => 'node_reference/autocomplete',
        'add_dialog' => 1,
        'edit_dialog' => 1,
        'search_dialog' => 0,
        'seach_dialog_view' => '',
      ),
    ),
  );
}

/**
 * Implements hook_widget_settings_form().
 */
function references_dialog_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $defaults = field_info_widget_settings($widget['type']);
  $settings = array_merge($defaults, $widget['settings']);
  $form = _references_dialog_get_original_widget_form($field, $instance);
  
  // Add our own additions.
  $form['add_dialog'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add dialog'),
    '#default_value' => $settings['add_dialog'],
    '#description' => t('Display an option to add a new node of the reference type that will be inserted into the field.'),
  );
  $form['edit_dialog'] = array(
    '#type' => 'checkbox',
    '#title' => t('Edit dialog'),
    '#default_value' => $settings['add_dialog'],
    '#description' => t('Display an option to edit the referenced node.'),
  );
  if (module_exists('views')) {
    $form['search_dialog'] = array(
      '#type' => 'checkbox',
      '#title' => t('Search dialog'),
      '#default_value' => $settings['search_dialog'],
      '#description' => t('Display an option to search for content.'),
    );
    $form['search_dialog_view'] = array(
      '#type' => 'select',
      '#options' => references_dialog_get_views_options($instance['entity_type']),
      '#title' => t('Search dialog view'),
      '#default_value' => !empty($settings['search_dialog_view']) ? $settings['search_dialog_view']: NULL,
      '#description' => t('Select which view should be used for the search dialog.'),
    );
  }
  return $form;
}

function _references_dialog_get_original_widget_form($field, $instance) {
  // Let's mask ourselves as the original reference autocomplete widget and get the
  // default settings.
  $instance['widget']['type'] = _references_dialog_get_autocomplete_type($field['type']);
  $form = node_reference_field_widget_settings_form($field, $instance);
  return $form;
}

function _references_dialog_get_autocomplete_type($field_type) {
  switch($field_type) {
    case 'taxonomy_term_reference':
      return 'taxonomy_autocomplete';
    case 'node_reference':
      return 'node_reference_autocomplete';
    case 'user_reference':
      return 'user_reference_autocomplete';
  }  
}

/**
 * Menu access checker for references_dialog
 */
function references_dialog_access($view) {
  return $view->access(array($view->current_display));
}

/**
 * Implements hook_field_widget_form().
 */
function references_dialog_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  // Let's mask ourselves as a node reference autocomplete widget and get the
  // default settings.
  $original_type = $instance['widget']['type'];
  $instance['widget']['type'] = 'node_reference_autocomplete';
  drupal_add_library('dialog', 'dialog');
  $element_form = node_reference_field_widget_form($form, $form_state, $field, $instance, $langcode, $items, $delta, $element);
  $form['#attached']['js'] = array(drupal_get_path('module', 'references_dialog') . '/js/references-dialog.js');
  $link_options = array('attributes' => array('class' => array('references-dialog-activate')));
  $dialog_links = array();
  // References provides the option to select which types are referenceable.
  if (isset($field['settings']['referenceable_types']))  {
    foreach ($field['settings']['referenceable_types'] as $type => $active) {
      if ($active !== 0) {
        if ($instance['widget']['settings']['add_dialog']) {
          $node_type = node_type_load($type);
          $dialog_links[] = array(
            'title' => t('Create @type', array('@type' => $node_type->name)),
            'href' => 'node/add/' . strtr($type, array('_' => '-')),
          ) + $link_options;
          $dialog_links['attributes']['class'][] = 'add-dialog';
        }
      }
    }
  }
  if ($instance['widget']['settings']['edit_dialog'] && isset($element_form['nid']['#default_value'])) {
    $dialog_links[] = array(
      'title' => t('Edit'), 
      'href' => 'node/' . $element_form['nid']['#default_value'] . '/edit'
    ) + $link_options;
    $dialog_links['attributes']['class'][] = 'edit-dialog';
  }
  if ($instance['widget']['settings']['search_dialog']) {
    $dialog_links[] = array(
      'title' => t('Search'),
      'href' => 'references/search/' . urlencode($instance['widget']['settings']['search_dialog_view']), 
    ) + $link_options;
    $dialog_links['attributes']['class'][] = 'search-dialog';
  }
  if (count($dialog_links)) {
    $element_form['dialog_links'] = array(
      '#type' => 'markup',
      '#markup' => theme('references_dialog_links', $dialog_links),
    );
  }
  return $element_form;
}

/**
 * Implements hook_theme().
 */
function references_dialog_theme() {
  return array( 
    'references_dialog_page' => array(
      'render element' => 'page',
      'template' => 'references-dialog-page',
    ),
    'references_dialog_links' => array(
      'variables' => array('links' => null),
    ),
  );
}

function references_dialog_entity_insert($entity, $entity_type) {
  if (references_dialog_in_dialog()) {
    references_dialog_close_on_redirect($entity, $entity_type);
  }
}

function references_dialog_entity_update($entity, $entity_type) {
  if (references_dialog_in_dialog()) {
    references_dialog_close_on_redirect($entity, $entity_type);
  }
}

/**
 * Sets our destination parameter so that the dialog will close itself after
 * redirect is completed.
 */
function references_dialog_close_on_redirect($entity, $entity_type) {
  $entity_info = entity_get_info($entity_type);
  // We use $_GET['destination'] since that overrides anything that happens
  // in the form. It is a hack, but it is very effective, since we don't have 
  // to be worried about getting overrun by other form submit handlers.
  $_GET['destination'] = 'references-dialog/redirect/' . 
  $entity->{$entity_info['entity keys']['id']} . '/' . 
  $entity_type .
  '?references-dialog-close=1&render=references-dialog';
}

/**
 * Implements hook_init().
 */
function references_dialog_init() {
  if (references_dialog_in_dialog()) {
    module_invoke_all('suppress');
    drupal_add_css(drupal_get_path('module', 'references_dialog') . '/css/references-dialog-search.css');
  }
}

/**
 * Menu callback for fetching a search view.
 * @param $view a view to use.
 */
function references_dialog_search_view($view) {
  $args = func_get_args();
  array_shift($args);
  // Load some helper javascript for this view.  
  return $view->execute_display($view->current_display, $args);
}

/**
 * Implements hook_page_alter().
 */
function references_dialog_page_alter(&$page) {
  if (references_dialog_in_dialog()) {
    $page['#theme'] = 'references_dialog_page';
  }
}

function references_dialog_in_dialog() {
  return isset($_GET['render']) && $_GET['render'] == 'references-dialog';
}

/**
 * Implements of hook_views_api().
 */
function references_dialog_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'reference_dialog') . '/views',
  );
}

/**
 * Implements of hook_views_plugins().
 */
function references_dialog_views_plugins() {
  return array(
    'display' => array(
      'references_dialog' => array(
        'title' => t('Reference Dialog Search'),
        'admin' => t('References'),
        'help' => t('A view that can be used when referencing content.'),
        'handler' => 'references_dialog_plugin_display',
        'help topic' => 'references-dialog',
        'uses hook menu' => TRUE,
        'references_dialog display' => TRUE,
        'path' => drupal_get_path('module', 'references_dialog') . '/views',
      ),
    ),
  );
}

/**
 * Retrieves the list of views with a 'references dialog' display,
 * in a format suitable for a 'select' form element.
 *
 * @param $entity_type
 *   The entity type.
 *
 * @return
 *   An array of eligible views displays.
 */
function references_dialog_get_views_options($entity_type) {
  // Filter views that contain a 'references' display. This actually returns a
  // list of displays (the same view appears several times).
  $displays = views_get_applicable_views('references_dialog display');

  // Filter views that list the entity type we want, and group the separate
  // displays by view.
  $entity_info = entity_get_info($entity_type);
  $options = array();
  foreach ($displays as $data) {
    list($view, $display_id) = $data;
    if ($view->base_table == $entity_info['base table']) {
      $options[$view->name . ':' . $display_id] = $view->name .' - ' . $view->display[$display_id]->display_title;
    }
  }
  return $options;
}

/**
 * Menu argument loader for a references dialog search view.
 * @param string $search_view 
 * A string containing the view name and the
 * display name separated by ':'
 * @return a loaded view with the right display set as the default display.
 */
function references_dialog_search_view_load($search_view) {
  list($view, $display) = explode(':', $search_view);
  $view = views_get_view($view);
  if ($view && isset($view->display[$display])) {
    // Set the current display here, that what we are going to use.
    $view->set_display($display);    
    return $view;
  }
  return FALSE;
}

function references_dialog_redirect_access() {
  // @todo It is not really a security issue, but we should probably check
  // that you can create the content you just created (silly), to access
  // this page.
  return TRUE;
}

function references_dialog_redirect_page($entity_id, $entity_type) {
  $entity = reset(entity_load($entity_type, array($entity_id)));
  $entity_info = entity_get_info($entity_type);
  $entity_id = $entity->{$entity_info['entity keys']['id']};
  $entity_title = $entity->{$entity_info['entity keys']['label']};
  if (isset($entity_id) && references_dialog_in_dialog() && isset($_GET['references-dialog-close'])) {
    drupal_add_js(drupal_get_path('module', 'references_dialog') . '/js/references-dialog-child.js');
    drupal_add_js(array(
      'ReferencesDialog' => array(
        'entity_id' => $entity_id,
        'title' => $entity_title,
      ),
    ), 'setting');
  }
  return '';
}

/**
 * Theme function for theming the links for opening
 * the references dialog.
 */
function theme_references_dialog_links($links) {
  return theme('links', array('links' => $links));
}